src/OfertaFone/ViewModels/Vitrine/DetailsViewModel.cs
using OfertaFone.WebUI.ViewModels.Base;

namespace OfertaFone.WebUI.ViewModels.Vitrine
{
    public class DetailsViewModel : ProdutoBaseViewModel
    {
        public string Image { get; set; }
    }
}

src/OfertaFone/ViewModels/Vitrine/IndexViewModel.cs
using OfertaFone.WebUI.ViewModels.Base;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace OfertaFone.WebUI.ViewModels.Vitrine
{
    public class IndexViewModel : BaseViewModel
    {
        public string Modelo { get; set; }
        public decimal Preco { get; set; }
        public bool Ativo { get; set; }
        public string Image { get; set; }
    }
}

src/OfertaFone/Controllers/VitrineController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfertaFone.Domain.Entities;
using OfertaFone.Domain.Interfaces;
using OfertaFone.Utils.Attributes;
using OfertaFone.WebUI.ViewModels.Components;
using OfertaFone.WebUI.ViewModels.Vitrine;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OfertaFone.WebUI.Controllers
{
    public class VitrineController : BaseController
    {
        private readonly IRepository<ProdutoEntity> _produtoRepository;
        private readonly IMapper _imapper;

        public VitrineController(
            IRepository<ProdutoEntity> produtoRepository,
            IMapper imapper)
        {
            this._produtoRepository = produtoRepository;
            this._imapper = imapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] int ps = 8, [FromQuery] int page = 1, [FromQuery] string q = null)
        {
            var catalogQuery = _produtoRepository.Table.AsQueryable();

            var catalog = await catalogQuery.AsNoTrackingWithIdentityResolution()
                                            .Where(x => EF.Functions.Like(x.Modelo, $"%{q}%") && x.Ativo == true)
                                            .OrderBy(x => x.Modelo)
                                            .Skip(ps * (page - 1))
                                            .Take(ps)
                                            .ToListAsync();

            var listView = catalog.Select(entity => _imapper.Map<IndexViewModel>(entity));

            var total = await catalogQuery.AsNoTrackingWithIdentityResolution()
                                          .Where(x => EF.Functions.Like(x.Modelo, $"%{q}%") && x.Ativo == true)
                                          .CountAsync();

            return View(new PagedViewModel<IndexViewModel>()
            {
                List = listView,
                TotalResults = total,
                PageIndex = page,
                PageSize = ps,
                Query = q
            });
        }

        // GET: ProdutoController/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            return View(_imapper.Map<DetailsViewModel>(await _produtoRepository.FindById(id)));
        }
    }
}

src/OfertaFone/ViewComponents/PagingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OfertaFone.WebUI.ViewModels.Components;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OfertaFone.WebUI.ViewComponents
{
    [ViewComponent(Name = "paging")]
    public class PagingViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IPagedList pagingModel)
        {
            return View(pagingModel);
        }
    }
}

src/OfertaFone/Views/Vitrine/Details.cshtml
@using OfertaFone.Utils.Extensions
@model OfertaFone.WebUI.ViewModels.Vitrine.DetailsViewModel

@{
    ViewData["Title"] = "Details";
    Layout = TipoLayout.LAYOUT_VITRINE;
}

<style>
    .container-detail {
        display: flex;
        flex-direction: column;
        width: 100%;
    }

    .information {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .img-produto {
        width: auto;
        margin: auto;
    }

    .descricao {
        display: flex;
        flex-direction: column;
        padding: 28px 40px;
        width: auto;
    }

    .product-prices {
        display: flex;
        flex-direction: column;
        border: 1px solid #d7d7d7;
        border-radius: 5px;
        padding: 15px 30px;
        align-items: center;
    }

    .price {
        margin-bottom: 25px;
        font-weight: bold;
        font-size: 25px;
    }

    .frete {
        display: flex;
        flex-direction: row;
    }

    .btn-comprar {
        margin-top: 76px;
    }

    .cep {
        margin-right: 12px;
    }

    .rating-stars {
        display: inline-block;
        vertical-align: middle;
        list-style: none;
        margin: 0;
        padding: 0;
        position: relative;
        white-space: nowrap;
        clear: both;
    }

    .rating-stars i {
        font-size: 14px;
        color: #ccc;
        display: inline;
    }

    .rating-stars li {
        display: block;
        text-overflow: clip;
        white-space: nowrap;
        z-index: 1;
    }

    .rating-stars li.stars-active {
        z-index: 2;
        position: absolute;
        top: 0;
        left: 0;
        overflow: hidden;
    }

    .rating-stars li.stars-active i {
        color: orange;
    }

    .content-body {
        -webkit-box-flex: 1;
        -ms-flex: 1 1 auto;
        flex: 1 1 auto;
        padding: 2rem 2.3rem;
    }

    .bg {
        background-color: #f8f9fa;
    }

    .price {
        font-weight: 600;
        color: #212529;
    }

</style>

<div class="container-detail">
    <div class="title">
        <h2>
            @Model.Modelo
            @Model.Marca
            @Model.Memoria
            @Model.Processador
            @Model.RAM
            @Model.Camera
        </h2>
    </div>
    <div class="information">
        <div class="img-produto">
            <img src="@Model.Image" alt="@Model.Marca">
        </div>
        <main class="col-md-6 border-left">
            <article class="content-body">
                <form asp-controller="carrinho" asp-route-id="@Model.Id" asp-action="adicionar" method="post">

                    <input asp-for="Id" hidden />

                    <h2 class="title">@Model.Modelo</h2>

                    <div class="rating-wrap my-3">
                        <ul class="rating-stars">
                            <li style="width: 80%" class="stars-active">
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                            <li>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                        </ul>
                        <small class="label-rating text-muted">132 estrelas</small>
                    </div>

                    <div class="mb-3">
                        <p class="price h4">@this.FormatMoney(@Model.Preco.Value)</p>
                    </div>

                    <h5>@Model.Descricao</h5>
                    <br />

                    <hr>
                    <br />

                    <button type="submit" class="btn btn-outline-primary">
                        <span class="text">Adicionar</span> <i class="fas fa-shopping-cart"> &nbsp;</i>
                    </button>
                    <a asp-action="Index" class="btn  btn-info">
                        <span class="text">Voltar</span>
                    </a>
                </form>
            </article>
        </main>
    </div>
</div>

src/OfertaFone/Views/Vitrine/Index.cshtml
@using OfertaFone.Utils.Extensions;
@model PagedViewModel<OfertaFone.WebUI.ViewModels.Vitrine.IndexViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = TipoLayout.LAYOUT_VITRINE;
}

<style>
    .content {
        background-image: url(assets/banners/Template.jpg);
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover
    }
</style>

<section>
    <div>
        <div class="content">
            <div style="text-align: center;">
                <div style="width:500px;height:300px;" />
            </div>
        </div>
    </div>
    <div class="container" style="padding-top: 20px">
        <div class="row">
            @{
                if (Model.List.Any())
                {
                    foreach (var produto in Model.List.OrderBy(p => p.Modelo))
                    {
                        <div class="col-md-3">
                            <div href="#" class="card card-product-grid">
                                <a asp-controller="vitrine" asp-action="details" asp-route-id="@produto.Id" class="img-wrap">
                                    <img src="@produto.Image" alt="@produto.Modelo">
                                </a>
                                <figcaption class="info-wrap">
                                    <a asp-controller="vitrine" asp-action="details" asp-route-id="@produto.Id" class="title">
                                        <b> @produto.Modelo</b>
                                    </a>
                                </figcaption>
                                <div class="card-footer price mt-1">
                                    <h3>@this.FormatMoney(produto.Preco)</h3>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <div class="col-md-12" style="text-align: center">
                        <h2>Oh não! 😮 <br> Não há produtos disponíveis.</h2>
                    </div>
                }
            }
        </div>

        <vc:paging paging-model="@Model"></vc:paging>

    </div>
</section>