src/OfertaFone/ViewModels/Components/LayoutNavBarViewModel.cs
using OfertaFone.WebUI.ViewModels.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OfertaFone.WebUI.ViewModels.Components
{
    public class LayoutNavBarViewModel : BaseViewModel
    {
        public string Email { get; set; }
        public string UserName { get; set; }
        public bool Enabled { get; set; }
        public string Image { get; set; }
    }
}

src/OfertaFone/Controllers/VitrineController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfertaFone.Domain.Entities;
using OfertaFone.Domain.Interfaces;
using OfertaFone.Utils.Attributes;
using OfertaFone.WebUI.ViewModels.Components;
using OfertaFone.WebUI.ViewModels.Vitrine;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OfertaFone.WebUI.Controllers
{
    public class VitrineController : BaseController
    {
        private readonly IRepository<ProdutoEntity> _produtoRepository;
        private readonly IMapper _imapper;

        public VitrineController(
            IRepository<ProdutoEntity> produtoRepository,
            IMapper imapper)
        {
            this._produtoRepository = produtoRepository;
            this._imapper = imapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] int ps = 8, [FromQuery] int page = 1, [FromQuery] string q = null)
        {
            var catalogQuery = _produtoRepository.Table.AsQueryable();

            var catalog = await catalogQuery.AsNoTrackingWithIdentityResolution()
                                            .Where(x => EF.Functions.Like(x.Modelo, $"%{q}%") && x.Ativo == true)
                                            .OrderBy(x => x.Modelo)
                                            .Skip(ps * (page - 1))
                                            .Take(ps)
                                            .ToListAsync();

            var listView = catalog.Select(entity => _imapper.Map<IndexViewModel>(entity));

            var total = await catalogQuery.AsNoTrackingWithIdentityResolution()
                                          .Where(x => EF.Functions.Like(x.Modelo, $"%{q}%") && x.Ativo == true)
                                          .CountAsync();

            return View(new PagedViewModel<IndexViewModel>()
            {
                List = listView,
                TotalResults = total,
                PageIndex = page,
                PageSize = ps,
                Query = q
            });
        }

        // GET: ProdutoController/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            return View(_imapper.Map<DetailsViewModel>(await _produtoRepository.FindById(id)));
        }
    }
}

src/OfertaFone/ViewComponents/LoginPartialViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OfertaFone.WebUI.Identity;
using OfertaFone.WebUI.ViewModels.Components;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OfertaFone.WebUI.ViewComponents
{
    [ViewComponent(Name = "LoginPartial")]
    public class LoginPartialViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public LoginPartialViewComponent(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var vm = new LoginPartialViewModel();

            if (HttpContext.User.Identity != null && HttpContext.User.Identity.Name != null)
            {
                var appUser = await _userManager.FindByNameAsync(
                HttpContext.User.Identity.Name);

                vm.Image = appUser?.Image;
            }

            return View("../Shared/_LoginPartial.cshtml", vm);
        }
    }
}

src/OfertaFone/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using OfertaFone.WebUI.Identity

<!DOCTYPE html>
<style>
    .section-footer ul a {
        color: inherit;
    }

    .header-main {
        position: relative;
        padding-top: 1rem;
        padding-bottom: 1rem;
    }

    .section-header .logo {
        max-height: 60px;
        width: auto;
    }
</style>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <link href="~/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OfertaFone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-4">
                        <a asp-action="Index" asp-controller="Vitrine" class="brand-wrap">
                            <img alt="OfertaFone" class="logo" src="~/assets/logo.png">
                        </a>
                    </div>
                    <div class="col-lg-5 col-sm-12">
                        <form method="get" asp-controller="Vitrine" asp-action="Index" class="search">
                            <div class="input-group w-100">
                                <input type="text" id="q" name="q" class="form-control" value="@ViewBag.Search" placeholder="O que você está procurando?">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <div class="d-flex justify-content-end">
                            @await Component.InvokeAsync("LoginPartial")
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div id="alertsModal"></div>

    <footer class="section-footer border-top p-3">
        <div class="container">
            <section class="footer-top padding-y">
                <div class="row">
                    <aside class="col-md-4">
                        <article class="mr-3">
                            <p class="logo-footer">OfertaFone</p>
                            <p class="mt-3">Um completo e-commerce para revenda dos seus usados.</p>
                            <div>
                                <a class="btn btn-icon btn-light" title="Facebook" target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-icon btn-light" title="Instagram" target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone"><i class="fab fa-instagram"></i></a>
                                <a class="btn btn-icon btn-light" title="Youtube" target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone"><i class="fab fa-youtube"></i></a>
                                <a class="btn btn-icon btn-light" title="GitHub" target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone"><i class="fab fa-github"></i></a>
                            </div>
                        </article>
                    </aside>
                    <aside class="col-sm-4 col-md-3">
                        <h6 class="title">Sobre</h6>
                        <ul class="list-unstyled">
                            <li> <a target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone">Sobre nós</a></li>
                            <li> <a target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone">Serviços</a></li>
                            <li> <a target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone">Termos de Uso</a></li>
                            <li> <a target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone">FAQ</a></li>
                        </ul>
                    </aside>
                    <aside class="col-sm-4 col-md-3">
                        <h6 class="title">Serviços</h6>
                        <ul class="list-unstyled">
                            <li> <a asp-controller="Order" asp-action="MyOrders">Minhas Compras</a></li>
                            <li> <a target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone">Perfil</a></li>
                            <li> <a target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone">Pedidos cancelados</a></li>
                            <li> <a target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone">Chargeback</a></li>
                        </ul>
                    </aside>
                    <aside class="col-sm-2  col-md-2">
                        <h6 class="title">Mobile</h6>
                        <a target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone" class="d-block mb-2"><img src="~/assets/misc/appstore.png" height="40"></a>
                        <a target="_blank" href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone" class="d-block mb-2"><img src="~/assets/misc/playmarket.png" height="40"></a>
                    </aside>
                </div>
            </section>

            <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column border-top">
                <div class="mb-2 mb-md-0 footer-copyright">
                    <p class="float-left text-muted"> ©2022, feito com 🧡 por OfertaFone Team</p>
                </div>
                <div>
                    <img src="~/assets/misc/payments.png" />
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/theme/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/theme/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/theme/assets/vendor/js/bootstrap.js"></script>
    <script src="~/theme/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/theme/assets/vendor/js/menu.js"></script>
    <script src="~/theme/assets/js/main.js"></script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
    <script>
        $('form').on('submit', function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).show();
        });

        $('.action-loading').click(function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).show();
        });

        $(document).ready(function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).hide();
        });

        window.onunload = function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).hide();
        };

        $(document).ajaxComplete(function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).hide();
        });

        $(function () {
            var alert = '@TempData["warning"]';
            var error = '@TempData["error"]';
            var sucess = '@TempData["success"]';
            var err = '';
            if (sucess != "" && sucess != null) {
                addSuccess(sucess);
            }
            if (alert != "" && alert != null) {
                addWarning(alert);
            }
            if (error != "" && error != null) {
                addError(error);
            }
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/OfertaFone/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html
  lang="en"
  class="light-style customizer-hide"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="~/theme/assets/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />
    <title>OfertaFone</title>
    <meta name="description" content="" />
    <link rel="icon" type="image/x-icon" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="~/theme/assets/vendor/fonts/boxicons.css" />
    <link rel="stylesheet" href="~/theme/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/theme/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/theme/assets/css/demo.css" />
    <link rel="stylesheet" href="~/theme/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
    <link rel="stylesheet" href="~/theme/assets/vendor/css/pages/page-auth.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/theme/assets/vendor/js/helpers.js"></script>
    <script src="~/theme/assets/js/config.js"></script>
  </head>
  <body>
    <div class="container-xxl">
      <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner">
          <div class="card">
            <div class="card-body">
                @RenderBody()
            </div>
          </div>
        </div>
      </div>
    </div>
    @await Html.PartialAsync("_LayoutLoading")
    <div id="alertsModal"></div>
    <script src="~/theme/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/theme/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/theme/assets/vendor/js/bootstrap.js"></script>
    <script src="~/theme/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/theme/assets/vendor/js/menu.js"></script>
    <script src="~/theme/assets/js/main.js"></script>
    <script src="~/js/site.js"></script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script>
        $('form').on('submit', function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).show();
        });

        $('.action-loading').click(function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).show();
        });

        $(document).ready(function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).hide();
        });

        window.onunload = function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).hide();
        };

        $(document).ajaxComplete(function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).hide();
        });

        $(function () {
            var alert = '@TempData["warning"]';
            var error = '@TempData["error"]';
            var sucess = '@TempData["success"]';
            var err = '';
            if (sucess != "" && sucess != null) {
                addSuccess(sucess);
            }
            if (alert != "" && alert != null) {
                addWarning(alert);
            }
            if (error != "" && error != null) {
                addError(error);
            }
        });
    </script> 
  </body>
</html>

src/OfertaFone/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html lang="en"
      class="light-style layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="~/theme/assets/"
      data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
    <title>OfertaFone</title>
    <meta name="description" content="" />
    <link rel="icon" type="image/x-icon" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />
    <link rel="stylesheet" href="~/theme/assets/vendor/fonts/boxicons.css" />
    <link rel="stylesheet" href="~/theme/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/theme/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/theme/assets/css/demo.css" />
    <link rel="stylesheet" href="~/theme/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/theme/assets/vendor/js/helpers.js"></script>
    <script src="~/theme/assets/js/config.js"></script>
</head>

<body>
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            @await Html.PartialAsync("_LayoutMenu")
            <div class="layout-page">
                @await Component.InvokeAsync("LayoutNavBarViewComponent")
                <div class="content-wrapper">
                    <div class="container-xxl flex-grow-1 container-p-y">
                        @RenderBody()
                    </div>
                    @await Html.PartialAsync("_LayoutFooterDashboard")
                    @await Html.PartialAsync("_LayoutLoading")
                    <div class="content-backdrop fade"></div>
                    <div id="alertsModal"></div>
                </div>
            </div>
        </div>
        <div class="layout-overlay layout-menu-toggle"></div>
    </div>

    <script src="~/theme/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/theme/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/theme/assets/vendor/js/bootstrap.js"></script>
    <script src="~/theme/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/theme/assets/vendor/js/menu.js"></script>
    <script src="~/theme/assets/js/main.js"></script>
    <script src="~/js/site.js"></script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>

    @RenderSection("Scripts", required: false)

    <script>
        $('form').on('submit', function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).show();
        });

        $('.action-loading').click(function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).show();
        });

        $(document).ready(function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).hide();
        });

        window.onunload = function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).hide();
        };

        $(document).ajaxComplete(function () {
            new bootstrap.Modal(document.getElementById("modalLoading"), {}).hide();
        });

        $(function () {
            var alert = '@TempData["warning"]';
            var error = '@TempData["error"]';
            var sucess = '@TempData["success"]';
            var err = '';
            if (sucess != "" && sucess != null) {
                addSuccess(sucess);
            }
            if (alert != "" && alert != null) {
                addWarning(alert);
            }
            if (error != "" && error != null) {
                addError(error);
            }
        });
    </script>
</body>
</html>

src/OfertaFone/Views/Shared/_LayoutFooterDashboard.cshtml
<footer class="content-footer footer bg-footer-theme">
    <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
        <div class="mb-2 mb-md-0">
            ©2022, feito com 🧡 por OfertaFone Team
        </div>
        <div>
            <a href="https://github.com/ICEI-PUC-Minas-PMV-ADS/oferta_fone" target="_blank" class="footer-link me-4">GitHub</a>
        </div>
    </div>
</footer>

src/OfertaFone/Views/Shared/_LayoutLoading.cshtml
<div class="modal fade" id="modalLoading" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" style="justify-content:center" role="document">
        <div class="text-center">
            <div class="loadingio-spinner-spin-vq59g8ryzdh"><div class="ldio-mej6n7e7g5f"><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div></div></div>
        </div>
  </div>
</div>

src/OfertaFone/Views/Shared/_LayoutMenu.cshtml
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a asp-controller="vitrine" asp-action="index" class="app-brand-link">
            <span class="app-brand-logo demo">
                <i class='bx bxs-book-content' style="FONT-SIZE: 28px;color: var(--font-menu) !important;"></i>
            </span>
            <span class="app-brand-text demo menu-text fw-bolder ms-2" style="text-align:center;text-transform:uppercase">OfertaFone</span>
        </a>
        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>
    <div class="menu-inner-shadow"></div>
    <ul class="menu-inner py-1">
        <li class="menu-item">
            <a asp-controller="home" asp-action="index" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div>Home</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-controller="account" asp-action="editprofile" class="menu-link">
                <i class="menu-icon tf-icons bx bx-user-pin"></i>
                <div>Perfil</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-controller="produto" asp-action="index" class="menu-link">
                <i class="menu-icon tf-icons bx bx-devices"></i>
                <div>Produto</div>
            </a>
        </li>
        <li class="menu-item">
            <a asp-controller="pedido" asp-action="index" class="menu-link">
                <i class='menu-icon tf-icons bx bx-package'></i>
                <div>Meus Pedidos</div>
            </a>
        </li>
    </ul>
</aside>

src/OfertaFone/Views/Shared/_LayoutNavBar.cshtml
@using OfertaFone.Utils.Extensions
@model LayoutNavBarViewModel

<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
     id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
            <i class="bx bx-menu bx-sm"></i>
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
        <div class="navbar-nav" style="color:black !important">
            @Model.Email
        </div>

        <!-- Search -->
        <div class="navbar-nav align-items-center">
            <div class="nav-item d-flex align-items-center" style="display:none !important">
                <i class="bx bx-search fs-4 lh-0"></i>
                <input type="text"
                       class="form-control border-0 shadow-none"
                       placeholder="Search..."
                       aria-label="Search..." />
            </div>
        </div>
        <!-- /Search -->

        <ul class="navbar-nav flex-row align-items-center ms-auto">
            <!-- Place this tag where you want the button to render. -->
            <li class="nav-item lh-1 me-3"></li>
            
            <!-- User -->
            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                        <img src="@Model.Image" alt="logo" class="w-px-40 h-auto rounded-circle" />
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <a class="dropdown-item" href="#">
                            <div class="d-flex">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar avatar-online">
                                        <img src="@Model.Image" alt="logo" class="w-px-40 h-auto rounded-circle" />
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <span class="fw-semibold d-block">@Context.User.Identity.Name</span>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" asp-action="EditProfile" asp-controller="Account">
                            <i class="bx bx-user me-2"></i>
                            <span class="align-middle">Meu Perfil</span>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" asp-action="Logout" asp-controller="Account">
                            <i class="bx bx-power-off me-2"></i>
                            <span class="align-middle">Log Out</span>
                        </a>
                    </li>
                </ul>
            </li>
            <!--/ User -->
        </ul>
    </div>
</nav>